from tkinter import *

root = Tk()
root.title('Loan')
formWidth = root.winfo_width()
print(formWidth)

tblHeader = Frame(root, bg='#fff', borderwidth=1, relief="solid")
lblHeader = Label(tblHeader, text='Table loan', font=("Courier", 32))

tblSndHead = Frame(root, bg='#fff')
lblBorrowHeader = Label(tblSndHead, text='Borrow money:', width=15, font=("Courier", 20), borderwidth=1, relief="solid")
lblMoneyHeader = Label(tblSndHead, text='$8000', width=5, font=("Courier", 20), borderwidth=1, relief="solid")
lblTypeHeader = Label(tblSndHead, text='Loan Type:', font=("Courier", 20), borderwidth=1, relief="solid")
lblDecreaseHeader = Label(tblSndHead, text='Decrease loan', font=("Courier", 20), borderwidth=1, relief="solid")
lblIRate = Label(tblSndHead, text='Interest rate:', width=15, font=("Courier", 20), borderwidth=1, relief="solid")
lblIMoney = Label(tblSndHead, text='1.5', width=5, font=("Courier", 20), borderwidth=1, relief="solid")
lblDuratation = Label(tblSndHead, text='Duration:', width=15, font=("Courier", 20), borderwidth=1, relief="solid")
lblMonth = Label(tblSndHead, text='12', width=5, font=("Courier", 20), borderwidth=1, relief="solid")

tblHeader.grid(row=0, column=0, columnspan=6)
lblHeader.grid(row=0, column=0)
tblSndHead.grid(row=1, column=0)
lblBorrowHeader.grid(row=1, column=0, columnspan=2)
lblMoneyHeader.grid(row=1, column=2)
lblTypeHeader.grid(row=1, column=3)
lblDecreaseHeader.grid(row=1, column=4)
lblIRate.grid(row=2, column=0, columnspan=2)
lblIMoney.grid(row=2, column=2)
lblDuratation.grid(row=3, column=0, columnspan=2)
lblMonth.grid(row=3, column=2)

headers = Frame(root, bg='#fff')
lblMm = Label(headers, text='mm', width=5, font=("Courier", 20), borderwidth=1, relief="solid")
lblOBal = Label(headers, text='Obal', width=10, font=("Courier", 20), borderwidth=1, relief="solid")
lblIR = Label(headers, text='IR', width=10, font=("Courier", 20), borderwidth=1, relief="solid")
lblDbal = Label(headers, text='Dbal', width=10, font=("Courier", 20), borderwidth=1, relief="solid")
lblPay = Label(headers, text='Pay', width=10, font=("Courier", 20), borderwidth=1, relief="solid")
lblEbal = Label(headers, text='Ebal', width=10, font=("Courier", 20), borderwidth=1, relief="solid")

headers.grid(row=4, column=0)
lblMm.grid(row=5, column=0)
lblOBal.grid(row=5, column=1)
lblIR.grid(row=5, column=2)
lblDbal.grid(row=5, column=3)
lblPay.grid(row=5, column=4)
lblEbal.grid(row=5, column=5)

root.mainloop()